In [9]:
import tensorflow as tf

In [10]:
scalar = tf.constant(1)
vector = tf.constant([1,2,3,4])
two_d_mat = tf.constant([[1,2,3,4],[5,6,7,8]])
three_d_mat = tf.constant([[[1,2,3], [1,2,4],],[[1,2,3], [1,2,4],],[[1,2,3], [1,2,4],]])
print(scalar, vector, two_d_mat, three_d_mat)

tf.Tensor(1, shape=(), dtype=int32) tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32) tf.Tensor(
[[[1 2 3]
  [1 2 4]]

 [[1 2 3]
  [1 2 4]]

 [[1 2 3]
  [1 2 4]]], shape=(3, 2, 3), dtype=int32)


In [12]:
vector = tf.Variable([1,2,3])
vector.assign([4,5,6])
print(vector)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4, 5, 6], dtype=int32)>


In [13]:
a = tf.constant(2)
b = tf.constant(3)
print(tf.add(a,b))
print(tf.multiply(a,b))

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
